# Generated by Django 2.1.2 on 2018-12-22 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 19, 48, 24, 609513, tzinfo=utc)),
        ),
    ]
