# Generated by Django 2.1.2 on 2018-12-22 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181222_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 19, 54, 52, 241554, tzinfo=utc)),
        ),
    ]
