# Generated by Django 2.1.4 on 2019-04-18 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181222_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 14, 41, 15, 823226, tzinfo=utc)),
        ),
    ]
