# Generated by Django 2.1.4 on 2019-04-18 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190418_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 15, 2, 43, 439414, tzinfo=utc)),
        ),
    ]
